---
groups:
  - name: postgres-exporter
    rules:
      - alert: PostgresExporterDown
        expr: up{job="postgres_exporter"} == 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: "PostgreSQL Exporter is unavailable on {{ $labels.instance }}"
          description: "Prometheus has failed to scrape PostgreSQL Exporter for 10 minutes."
      - alert: PostgresDatabaseUnavailable
        expr: pg_up{job="postgres_exporter"} == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "PostgreSQL is unavailable from {{ $labels.instance }}"
          description: "The exporter has reported that PostgreSQL is unreachable for 5 minutes."
