---
groups:
  - name: promtail
    rules:
      - alert: PromtailDown
        expr: up{job="promtail"} == 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: "Promtail is unavailable on {{ $labels.instance }}"
          description: "Prometheus has failed to scrape Promtail for 10 minutes."
